### PR TITLE
Support for custom nuspec name

### PR DESCRIPTION
**Pull request by hmemcpy**
+ specifying a correct GitVersionTask dependency

### CODE REVIEW

**Comment by hmemcpy** [comment]
@Particular/nservicebus-maintainers please review

**Comment by danielmarbach** [comment]
Would it make sense to split this into two PRs?

**Comment by hmemcpy** [comment]
@danielmarbach yes, you're right. I'll move the nuspec bump to another PR

**Comment by hmemcpy** [comment]
Done https://github.com/Particular/NuGetPackager/pull/22

**Pull request merged**
